# Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6508am3jp1c73c57010-a.singapore-postgres.render.com/money_manager_psql?ssl=true&sslmode=require
spring.datasource.username=money_manager_psql_user
spring.datasource.password=s1lMZtbvpIqkob0fTFUC1ZBAXxLof8Xv

# Context Path
server.servlet.context-path=/api/v1.0

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=amir2008-super-secret-key-for-jwt-token-generation-2026

logging.level.org.springframework.security=DEBUG